apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-ops
  namespace: back-ops
  labels:
    app: back-ops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: back-ops
  template:
    metadata:
      labels:
        app: back-ops
    spec:
      volumes:
      - name: gcp-key-vol
        secret:
          secretName: back-gcp-secret
          items:
          - key: key.json
            path: key.json
      containers:
      - name: back-ops-container
        image: public.ecr.aws/t7q9p8g1/lotus-maket/spring:latest
        ports:
        - containerPort: 8765
        imagePullPolicy: Always
        volumeMounts:
        - name: gcp-key-vol
          mountPath: /app/key.json
          subPath: key.json
          readOnly: true
        envFrom:
        - configMapRef:
            name: back-ops-cm
        env:
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: back-db-secret
              key: MONGO_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: back-db-secret
              key: MONGO_PASSWORD

