version: 0.2

phases:
  install:
    commands:
      # CodeBuild 환경에 SSH 클라이언트가 없을 수도 있으므로 설치
      - yum update -y
      - yum install -y openssh-clients

  post_build:
    commands:
      - echo "=== Save Bastion SSH key ==="
      # CodeBuild 환경 변수 $BASTION_PRIVATE_KEY 를 파일로 저장
      - echo "$BASTION_PRIVATE_KEY" > bastion.pem
      - chmod 400 bastion.pem

      # 호스트, 키 파일 경로 등을 변수로 지정 (필요시 수정)
      - BASTION_HOST="54.180.140.42"
      - KEY_FILE="bastion.pem"

      - echo "=== Connect to Bastion Host and run commands ==="
      # 1) 베스천 호스트에서 kubeconfig 업데이트
      - ssh -o StrictHostKeyChecking=no ec2-user@$BASTION_HOST -i $KEY_FILE "aws eks update-kubeconfig --region ap-northeast-2 --name lotus-market"

      - ssh -o StrictHostKeyChecking=no ec2-user@$BASTION_HOST -i $KEY_FILE "kubectl apply -f /home/ec2-user/k8s-lotus-market/db-ops/"
      - ssh -o StrictHostKeyChecking=no ec2-user@$BASTION_HOST -i $KEY_FILE "kubectl apply -f /home/ec2-user/k8s-lotus-market/back-ops/"
      - ssh -o StrictHostKeyChecking=no ec2-user@$BASTION_HOST -i $KEY_FILE "kubectl apply -f /home/ec2-user/k8s-lotus-market/front-ops/"

artifacts:
  files:
    - '**/*'

