version: 0.2

env:
  variables:
    REPOSITORY_URL1: public.ecr.aws/t7q9p8g1/lotus-market/next
    REPOSITORY_URL2: public.ecr.aws/t7q9p8g1/lotus-market/spring
    REPOSITORY_URL3: public.ecr.aws/t7q9p8g1/lotus-market/db

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon Public ECR..."
      - "aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin $REPOSITORY_URL1"
      - "aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin $REPOSITORY_URL2"
      - "aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin $REPOSITORY_URL3"

  build:
    commands:
      - echo "Build started on $(date)"
      
      # Extract tags from docker-compose.yml
      - NEXT_APP_IMAGE_TAG=$(grep "image: dealim/lotus-market-next" docker-compose.yml | awk -F':' '{print $3}')
      - SPRING_APP_IMAGE_TAG=$(grep "image: dealim/lotus-market-spring" docker-compose.yml | awk -F':' '{print $3}')
      - MONGO_DB_IMAGE_TAG=$(grep "image: dealim/lotus-market-mongo" docker-compose.yml | awk -F':' '{print $3}')
      
      # Build next-app
      - echo "Building the Docker image for next-app..."
      - "docker build -f apps/next-app/Dockerfile -t dealim/lotus-market-next:$NEXT_APP_IMAGE_TAG ./apps/next-app || { echo 'next-app build failed'; exit 1; }"
      - "docker tag dealim/lotus-market-next:$NEXT_APP_IMAGE_TAG $REPOSITORY_URL1:$NEXT_APP_IMAGE_TAG"

      # Build spring-app
      - echo "Building the Docker image for spring-app..."
      - "docker build -f apps/spring-app/Dockerfile -t dealim/lotus-market-spring:$SPRING_APP_IMAGE_TAG ./apps/spring-app || { echo 'spring-app build failed'; exit 1; }"
      - "docker tag dealim/lotus-market-spring:$SPRING_APP_IMAGE_TAG $REPOSITORY_URL2:$SPRING_APP_IMAGE_TAG"

      # Build mongo-db
      - echo "Building the Docker image for mongo-db..."
      - "docker build -f apps/mongo-db/Dockerfile -t dealim/lotus-market-mongo:$MONGO_DB_IMAGE_TAG ./apps/mongo-db || { echo 'mongo-db build failed'; exit 1; }"
      - "docker tag dealim/lotus-market-mongo:$MONGO_DB_IMAGE_TAG $REPOSITORY_URL3:$MONGO_DB_IMAGE_TAG"

  post_build:
    commands:
      - echo "Build completed on $(date)"
      - echo "Pushing the Docker images..."

      # Push next-app image
      - "docker push $REPOSITORY_URL1:$NEXT_APP_IMAGE_TAG || { echo 'Failed to push next-app image'; exit 1; }"
  
      # Push spring-app image
      - "docker push $REPOSITORY_URL2:$SPRING_APP_IMAGE_TAG || { echo 'Failed to push spring-app image'; exit 1; }"

      # Push mongo-db image
      - "docker push $REPOSITORY_URL3:$MONGO_DB_IMAGE_TAG || { echo 'Failed to push mongo-db image'; exit 1; }"
      
artifacts:
  files:
    - '**/*'
