version: 0.2

phases:
  post_build:
    commands:
      # EKS Deployment
      - aws eks update-kubeconfig --region ap-northeast-2 --name lotus-market

      - echo "Current IAM caller identity:"
      - aws sts get-caller-identity

      - AWS_ECR_URI1=$REPOSITORY_URL1:latest
      - AWS_ECR_URI2=$REPOSITORY_URL2:latest
      - AWS_ECR_URI3=$REPOSITORY_URL3:latest
      - DATE=`date`
      - echo Build completed on $DATE
      - sed -i.bak 's#AWS_ECR_URI#'"$AWS_ECR_URI"'#' k8s/front-ops/front-ops-deploy.yaml
      - sed -i.bak 's#AWS_ECR_URI#'"$AWS_ECR_URI"'#' k8s/back-ops/back-ops-deploy.yaml
      - sed -i.bak 's#AWS_ECR_URI#'"$AWS_ECR_URI"'#' k8s/db-ops/db-ops-deploy.yaml
      - echo "=== Debug network connectivity ==="
      - nslookup https://6BDC074A9086DFD0FEF96808053A531F.gr7.ap-northeast-2.eks.amazonaws.com || true
      - curl -kv https://6BDC074A9086DFD0FEF96808053A531F.gr7.ap-northeast-2.eks.amazonaws.com || true
      - nc -vz 192.168.152.251 443 || true
      - nc -vz 192.168.136.139 443 || true
      - kubectl apply -f k8s/db-ops/
      - kubectl apply -f k8s/back-ops/
      - kubectl apply -f k8s/front-ops/

artifacts:
  files:
    - '**/*'
