services:
  spring-app:
    build:
      context: ./bck-post-ns/spring-lotus-market/
      dockerfile: Dockerfile
    ports:
      - "${LOTUS_DB_PORT}:${LOTUS_DB_PORT}" 
    environment:
      DB_USERNAME: "${DB_USERNAME}"
      DB_PASSWORD: "${DB_PASSWORD}"
      LOTUS_DB_URL: "next-app:27017"

  next-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${EXPOSE_PORT}:${SERVER_PORT}" 
    environment:
      SPRING_PROFILES_ACTIVE: "${SPRING_PROFILES_ACTIVE}"
      SERVER_PORT: "${SERVER_PORT}"
