apiVersion: v1
kind: Service
metadata:
  name: front-ops-svc
  namespace: front-ops
  labels:
    app: front-ops
spec:
  selector:
    app: front-ops
  type: NodePort
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 31000
status:
  loadBalancer: {}
