apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-ops
  namespace: front-ops
  labels:
    app: front-ops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: front-ops
  template:
    metadata:
      labels:
        app: front-ops
    spec:
      containers:
      - name: front-ops-container
        image: dealim/lotus-market-next:1.4
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: "2"
            memory: "2Gi"
          limits:
            cpu: "4"
            memory: "8Gi"
        env:
        - name: API_SERVER_URL
          valueFrom:
            configMapKeyRef:
              name: front-ops-cm
              key: API_SERVER_URL
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: front-ops-hpa
  namespace: front-ops
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: front-ops
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
