apiVersion: v1
kind: ResourceQuota
metadata:
  name: front-ops-rq
  namespace: front-ops
spec:
  hard:
    requests.cpu: "2"     
    requests.memory: "2Gi"
    limits.cpu: "4"          
    limits.memory: "8Gi"    
---
apiVersion: v1
kind: LimitRange
metadata:
  name: front-ops-lr
  namespace: front-ops
spec:
  limits:
  - type: Container
    defaultRequest:
      cpu: "2"
      memory: "2Gi"
    default:
      cpu: "4"
      memory: "8Gi"
    max:
      cpu: "4"
      memory: "8Gi"
