apiVersion: v1
kind: ResourceQuota
metadata:
  name: front-ops-rq
  namespace: front-ops
spec:
  hard:
    requests.cpu: "2"     
    requests.memory: "2Gi"
    limits.cpu: "2"          
    limits.memory: "6Gi"    
---
apiVersion: v1
kind: LimitRange
metadata:
  name: front-ops-lr
  namespace: front-ops
spec:
  limits:
  - type: Container
    defaultRequest:
      cpu: "2"
      memory: "3Gi"
    default:
      cpu: "2"
      memory: "3Gi"
    max:
      cpu: "2"
      memory: "6Gi"
