apiVersion: v1
kind: ResourceQuota
metadata:
  name: front-dev-rq
  namespace: front-dev
spec:
  hard:
    requests.cpu: "1"         
    requests.memory: "512Mi"
    limits.cpu: "1"        
    limits.memory: "1Gi"  
---
apiVersion: v1
kind: LimitRange
metadata:
  name: front-dev-lr
  namespace: front-dev
spec:
  limits:
  - type: Container
    defaultRequest:
      cpu: "1"           
      memory: "512Mi"  
    default:
      cpu: "1"        
      memory: "1Gi"  
    max:
      cpu: "1"
      memory: "1Gi"
