apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-dev
  namespace: db-dev
  labels:
    app: db-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-dev
  strategy: {}
  template:
    metadata:
      labels:
        app: db-dev
    spec:
      volumes:
      - name: mongo-pv-storage
        persistentVolumeClaim:
          claimName: db-dev-mongo-pvc
      containers:
      - name: db-dev-container
        image: seunghunn/test-mongo:1.0
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-pv-storage
          mountPath: /data/db
        resources:
          requests:
            cpu: "1"
            memory: "1Gi"
          limits:
            cpu: "2"
            memory: "4Gi"
