spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  application:
    name: lotus-market

  data:
    mongodb:
      uri: mongodb://${DB_USERNAME}:${DB_PASSWORD}@${DB_URL:localhost:27017}/lotus-db?authSource=lotus-db

server:
  port: 8765

# logging:
#   level:
#     org:
#       mongodb:
#         driver: TRACE
#       springframework:
#         data:
#           mongodb:
#             core: DEBUG

gcp:
  bucket:
    name: k8s-kimjc