apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-dev
  namespace: back-dev
  labels:
    app: back-ops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: back-dev
  template:
    metadata:
      labels:
        app: back-dev
    spec:
      volumes:
      - name: gcp-key-vol
        secret:
          secretName: back-gcp-secret
          items:
          - key: key.json
            path: key.json
      containers:
      - image: dealim/lotus-market-spring:1.8
        name: back-dev-container
        ports:
        - containerPort: 8765
        volumeMounts:
        - name: gcp-key-vol
          mountPath: /app/key.json
          subPath: key.json
          readOnly: true
        envFrom:
        - configMapRef:
            name: back-dev-cm
        env:
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: back-db-secret
              key: MONGO_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: back-db-secret
              key: MONGO_PASSWORD
        resources:
          requests:
            cpu: "1"
            memory: "512Mi"
          limits:
            cpu: "2"
            memory: "1Gi"
