apiVersion: v1
kind: ResourceQuota
metadata:
  name: back-dev-rq
  namespace: back-dev
spec:
  hard:
    requests.cpu: "1"
    requests.memory: "512Mi"
    limits.cpu: "2"
    limits.memory: "1Gi"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: back-dev-lr
  namespace: back-dev
spec:
  limits:
  - type: Container
    defaultRequest:
      cpu: "1"
      memory: "512Mi"
    default:
      cpu: "2"
      memory: "1Gi"
    max:
      cpu: "2"
      memory: "1Gi"
