spring:
  application:
    name: lotus-market

  data:
    mongodb:
      uri: mongodb://${DB_USERNAME}:${DB_PASSWORD}@${DB_URL:localhost:27017}/lotus-db

server:
  port: 8765

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core: DEBUG

gcp:
  bucket:
    name: k8s-kimjc
