apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: mongo
  name: mongo-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mongo
    spec:
      nodeSelector:
        kubernetes.io/hostname: k8s-node3

      volumes:
        - name: db-data
          hostPath:
            path: /var/lib/lotus-market-db
        
      containers:
        - image: dealim/lotus-market-mongo:1.0
          name: lotus-market-db
          ports:
          - containerPort: 27017

---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: mongo
  name: mongo-svc
spec:
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    app: mongo
