apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-ops
  namespace: db-ops
  labels:
    app: db-ops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-ops
  strategy: {}
  template:
    metadata:
      labels:
        app: db-ops
    spec:
      volumes:
      - name: mongo-pv-storage
        persistentVolumeClaim:
          claimName: db-ops-mongo-pvc
      containers:
      - name: db-ops-container
        image: AWS_ECR_URI3
        ports:
        - containerPort: 27017
        imagePullPolicy: Always
        volumeMounts:
          - name: mongo-pv-storage
            mountPath: /data/db
