apiVersion: v1
kind: ResourceQuota
metadata:
  name: db-ops-rq
  namespace: db-ops
spec:
  hard:
    requests.cpu: "1"
    requests.memory: "1Gi"
    limits.cpu: "2"
    limits.memory: "4Gi"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: db-ops-lr
  namespace: db-ops
spec:
  limits:
  - type: Container
    defaultRequest:
      cpu: "1"
      memory: "1Gi"
    default:
      cpu: "2"
      memory: "4Gi"
    max:
      cpu: "2"
      memory: "4Gi"
