services:
  backend:
    image: dealim/lotus-market-spring:2.0
    build:
      context: ./spring-app/
      dockerfile: Dockerfile-dev
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_URL=db:27017
      - GOOGLE_APPLICATION_CREDENTIALS=/app/key.json
      - GOOGLE_CLOUD_PROJECT=k8s-kimjc
    volumes:
      - ~/.config/gcloud/application_default_credentials.json:/app/key.json
      - ./spring-app/src:/app/src
    ports:
      - "8765:8765"
    depends_on:
      - db

  db:
    image: dealim/lotus-market-mongo:1.3
    build:
      context: ./mongo-db/
      dockerfile: ./Dockerfile
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ./mongo-db/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
    ports:
      - "27017:27017"

  front:
    image: dealim/lotus-market-next:1.5
    build:
      context: ./next-app/
      dockerfile: ./Dockerfile
    environment:
      - API_SERVER_URL=backend:8765 
    ports:
      - "3000:3000"
    volumes:
      - ./next-app/src/:/app/src/

volumes:
  grafana-data:
