apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: next
  name: next-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: next
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: next
    spec:
      containers:
      - image: dealim/lotus-market-next:1.4
        name: lotus-market-next
        ports:
        - containerPort: 3000
        env:
        - name: API_SERVER_URL
          valueFrom:
            configMapKeyRef:
              name: next-cm
              key: API_SERVER_URL
            
status: {}
---

apiVersion: v1
data:
  API_SERVER_URL: spring-svc:8765
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: next-cm

---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: next
  name: next-svc
spec:
  ports:
  - port: 3000
    nodePort: 30000
    protocol: TCP
    targetPort: 3000
  selector:
    app: next
  type: NodePort
status:
  loadBalancer: {}
